
create table if not exists public.saved_articles (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  article_id text not null,
  title text not null,
  link text not null,
  source text,
  category text,
  summary text,
  created_at timestamptz default now(),
  unique(user_id, article_id)
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  language text default 'en',
  created_at timestamptz default now()
);

alter table public.saved_articles enable row level security;
alter table public.newsletter_subscribers enable row level security;

create policy "Users can manage own saved"
on public.saved_articles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Anyone can subscribe newsletter"
on public.newsletter_subscribers for insert with check (true);
