create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  preferred_language text default 'en',
  role text default 'reader' check (role in ('reader', 'editor', 'admin')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.saved_articles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id text not null,
  title text not null,
  link text not null,
  source text,
  category text,
  summary text,
  image_url text,
  published_at timestamptz,
  created_at timestamptz default now(),
  unique(user_id, article_id)
);

create table if not exists public.reading_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id text not null,
  title text not null,
  link text not null,
  source text,
  category text,
  read_at timestamptz default now()
);

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  language text default 'en',
  status text default 'pending' check (status in ('pending', 'active', 'unsubscribed')),
  frequency text default 'daily' check (frequency in ('daily', 'weekly')),
  country text default 'IN',
  categories text[] default array['top','local','business','tech','sports'],
  consent_text text,
  opt_in_token text,
  unsubscribe_token text,
  confirmed_at timestamptz,
  unsubscribed_at timestamptz,
  source text default 'site',
  created_at timestamptz default now()
);

alter table public.newsletter_subscribers add column if not exists frequency text default 'daily' check (frequency in ('daily', 'weekly'));
alter table public.newsletter_subscribers add column if not exists country text default 'IN';
alter table public.newsletter_subscribers add column if not exists categories text[] default array['top','local','business','tech','sports'];
alter table public.newsletter_subscribers add column if not exists consent_text text;
alter table public.newsletter_subscribers add column if not exists opt_in_token text;
alter table public.newsletter_subscribers add column if not exists unsubscribe_token text;
alter table public.newsletter_subscribers add column if not exists confirmed_at timestamptz;
alter table public.newsletter_subscribers add column if not exists unsubscribed_at timestamptz;
alter table public.newsletter_subscribers alter column status set default 'pending';
alter table public.newsletter_subscribers drop constraint if exists newsletter_subscribers_status_check;
alter table public.newsletter_subscribers add constraint newsletter_subscribers_status_check check (status in ('pending', 'active', 'unsubscribed'));

create table if not exists public.user_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  preferred_country text default 'IN',
  preferred_categories text[] default array['top','local','business','tech','sports'],
  digest_frequency text default 'daily' check (digest_frequency in ('daily', 'weekly', 'off')),
  email_notifications boolean default false,
  push_notifications boolean default false,
  marketing_consent boolean default false,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.user_preferences add column if not exists metadata jsonb default '{}'::jsonb;

create table if not exists public.email_digest_logs (
  id bigint generated by default as identity primary key,
  digest_type text not null check (digest_type in ('daily', 'weekly')),
  recipient_email text,
  country text default 'IN',
  categories text[] default array['top','local','business','tech','sports'],
  article_ids text[] default '{}',
  subject text,
  status text default 'generated' check (status in ('generated', 'sent', 'skipped', 'error')),
  message text,
  created_at timestamptz default now()
);

create table if not exists public.rss_sources (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  url text not null unique,
  language text default 'en',
  country text default 'IN',
  priority integer default 0,
  enabled boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.adsense_slots (
  id uuid primary key default gen_random_uuid(),
  slot_key text unique not null,
  placement text not null,
  format text not null,
  enabled boolean default true,
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.affiliate_links (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null,
  destination_url text not null,
  network text default 'direct',
  image_url text,
  disclosure text default 'Nuzenio may earn a commission from this link.',
  enabled boolean default false,
  approved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.affiliate_links add column if not exists network text default 'direct';
alter table public.affiliate_links add column if not exists image_url text;

create table if not exists public.sponsored_blocks (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  sponsor_name text not null,
  category text default 'all',
  placement text default 'sidebar',
  destination_url text not null,
  image_url text,
  disclosure text default 'Sponsored content',
  label text default 'Sponsored',
  enabled boolean default false,
  start_at timestamptz,
  end_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.ai_settings (
  key text primary key default 'global',
  enabled boolean default true,
  categories text[] default array['top','world','business','tech','ai','sports','health','science','entertainment','local'],
  simple_brief_enabled boolean default true,
  comparison_enabled boolean default true,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.news_cache (
  id uuid primary key default gen_random_uuid(),
  article_id text not null,
  title text not null,
  link text not null,
  source text,
  summary text,
  image text,
  image_kind text default 'logo',
  category text not null,
  country text not null,
  published_at timestamptz,
  payload jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(article_id, category, country)
);

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  event_name text not null,
  article_id text,
  category text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.correction_reports (
  id uuid primary key default gen_random_uuid(),
  article_id text,
  article_title text,
  article_source text,
  article_link text,
  reporter_email text,
  issue_type text default 'incorrect',
  details text,
  status text default 'new',
  correction_notice text,
  reviewed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_table text,
  target_id text,
  status text default 'ok' check (status in ('ok', 'error')),
  message text,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.publisher_profiles (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  logo_url text,
  homepage_url text,
  country text default 'GLOBAL',
  categories text[] default '{}',
  credibility_profile jsonb default '{}'::jsonb,
  status text default 'active' check (status in ('active', 'review', 'disabled')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.journalist_profiles (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  full_name text not null,
  role text default 'Contributor',
  bio text,
  avatar_url text,
  publisher_slug text default 'nuzenio',
  expertise text[] default '{}',
  social_links jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.original_articles (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  title text not null,
  dek text,
  body text,
  content_type text default 'analysis' check (content_type in ('analysis', 'explainer', 'fact_check', 'opinion', 'research')),
  status text default 'draft' check (status in ('draft', 'review', 'scheduled', 'published', 'archived')),
  author_slug text,
  publisher_slug text default 'nuzenio',
  category text default 'top',
  tags text[] default '{}',
  opinion_label boolean default false,
  fact_check_status text,
  scheduled_at timestamptz,
  published_at timestamptz,
  approved_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.original_article_revisions (
  id uuid primary key default gen_random_uuid(),
  article_id uuid references public.original_articles(id) on delete cascade,
  editor_id uuid references auth.users(id) on delete set null,
  revision_note text,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.editorial_workflow_logs (
  id bigint generated by default as identity primary key,
  article_id uuid references public.original_articles(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  status text,
  message text,
  created_at timestamptz default now()
);

create table if not exists public.user_interests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  interest text not null,
  interest_type text default 'topic' check (interest_type in ('topic', 'entity', 'source', 'author', 'country', 'category')),
  weight numeric default 1,
  source text default 'user' check (source in ('user', 'reading_history', 'saved_article', 'system')),
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(user_id, interest_type, interest)
);

create table if not exists public.followed_topics (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  topic text not null,
  created_at timestamptz default now(),
  unique(user_id, topic)
);

create table if not exists public.followed_entities (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  entity text not null,
  entity_type text default 'entity',
  created_at timestamptz default now(),
  unique(user_id, entity)
);

create table if not exists public.followed_sources (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  source text not null,
  source_slug text,
  created_at timestamptz default now(),
  unique(user_id, source)
);

create table if not exists public.followed_authors (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  author_slug text not null,
  created_at timestamptz default now(),
  unique(user_id, author_slug)
);

create table if not exists public.recommendation_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  article_id text,
  title text,
  source text,
  category text,
  score numeric,
  reason text,
  algorithm text default 'nuzenio-v13',
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.ai_briefs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  brief_type text default 'morning' check (brief_type in ('morning', 'evening', 'weekly', 'top10')),
  country text default 'IN',
  categories text[] default '{}',
  title text not null,
  summary text,
  story_ids text[] default '{}',
  status text default 'draft' check (status in ('draft', 'ready', 'sent', 'archived')),
  scheduled_at timestamptz,
  sent_at timestamptz,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

alter table public.profiles enable row level security;
alter table public.saved_articles enable row level security;
alter table public.reading_history enable row level security;
alter table public.newsletter_subscribers enable row level security;
alter table public.user_preferences enable row level security;
alter table public.email_digest_logs enable row level security;
alter table public.rss_sources enable row level security;
alter table public.adsense_slots enable row level security;
alter table public.affiliate_links enable row level security;
alter table public.sponsored_blocks enable row level security;
alter table public.ai_settings enable row level security;
alter table public.news_cache enable row level security;
alter table public.analytics_events enable row level security;
alter table public.correction_reports enable row level security;
alter table public.admin_logs enable row level security;
alter table public.publisher_profiles enable row level security;
alter table public.journalist_profiles enable row level security;
alter table public.original_articles enable row level security;
alter table public.original_article_revisions enable row level security;
alter table public.editorial_workflow_logs enable row level security;
alter table public.user_interests enable row level security;
alter table public.followed_topics enable row level security;
alter table public.followed_entities enable row level security;
alter table public.followed_sources enable row level security;
alter table public.followed_authors enable row level security;
alter table public.recommendation_logs enable row level security;
alter table public.ai_briefs enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

drop policy if exists "Profiles are readable by owner" on public.profiles;
drop policy if exists "Users update own profile" on public.profiles;
drop policy if exists "Users can manage own saved articles" on public.saved_articles;
drop policy if exists "Users can manage own reading history" on public.reading_history;
drop policy if exists "Anyone can subscribe to newsletter" on public.newsletter_subscribers;
drop policy if exists "Subscribers can read own email row" on public.newsletter_subscribers;
drop policy if exists "Users can manage own preferences" on public.user_preferences;
drop policy if exists "RSS sources are publicly readable" on public.rss_sources;
drop policy if exists "Ad slots are publicly readable" on public.adsense_slots;
drop policy if exists "Approved affiliate links are publicly readable" on public.affiliate_links;
drop policy if exists "Enabled sponsored blocks are publicly readable" on public.sponsored_blocks;
drop policy if exists "AI settings are publicly readable" on public.ai_settings;
drop policy if exists "News cache is publicly readable" on public.news_cache;
drop policy if exists "Users can insert analytics events" on public.analytics_events;
drop policy if exists "Anyone can report corrections" on public.correction_reports;
drop policy if exists "Admins can manage correction reports" on public.correction_reports;
drop policy if exists "Admins can manage profiles" on public.profiles;
drop policy if exists "Admins can read saved articles" on public.saved_articles;
drop policy if exists "Admins can read reading history" on public.reading_history;
drop policy if exists "Admins can manage rss sources" on public.rss_sources;
drop policy if exists "Admins can manage ad slots" on public.adsense_slots;
drop policy if exists "Admins can manage affiliate links" on public.affiliate_links;
drop policy if exists "Admins can manage sponsored blocks" on public.sponsored_blocks;
drop policy if exists "Admins can manage AI settings" on public.ai_settings;
drop policy if exists "Admins can manage news cache" on public.news_cache;
drop policy if exists "Admins can read newsletter subscribers" on public.newsletter_subscribers;
drop policy if exists "Admins can manage newsletter subscribers" on public.newsletter_subscribers;
drop policy if exists "Admins can read user preferences" on public.user_preferences;
drop policy if exists "Admins can manage email digest logs" on public.email_digest_logs;
drop policy if exists "Admins can read analytics events" on public.analytics_events;
drop policy if exists "Admins can read admin logs" on public.admin_logs;
drop policy if exists "Admins can insert admin logs" on public.admin_logs;
drop policy if exists "Active publisher profiles are public" on public.publisher_profiles;
drop policy if exists "Journalist profiles are public" on public.journalist_profiles;
drop policy if exists "Published original articles are public" on public.original_articles;
drop policy if exists "Admins can manage publisher profiles" on public.publisher_profiles;
drop policy if exists "Admins can manage journalist profiles" on public.journalist_profiles;
drop policy if exists "Admins can manage original articles" on public.original_articles;
drop policy if exists "Admins can manage original revisions" on public.original_article_revisions;
drop policy if exists "Admins can manage editorial workflow logs" on public.editorial_workflow_logs;
drop policy if exists "Users can manage own interests" on public.user_interests;
drop policy if exists "Users can manage own followed topics" on public.followed_topics;
drop policy if exists "Users can manage own followed entities" on public.followed_entities;
drop policy if exists "Users can manage own followed sources" on public.followed_sources;
drop policy if exists "Users can manage own followed authors" on public.followed_authors;
drop policy if exists "Users can read own recommendation logs" on public.recommendation_logs;
drop policy if exists "Users can insert own recommendation logs" on public.recommendation_logs;
drop policy if exists "Users can manage own AI briefs" on public.ai_briefs;
drop policy if exists "Admins can read user interests" on public.user_interests;
drop policy if exists "Admins can read followed topics" on public.followed_topics;
drop policy if exists "Admins can read followed entities" on public.followed_entities;
drop policy if exists "Admins can read followed sources" on public.followed_sources;
drop policy if exists "Admins can read followed authors" on public.followed_authors;
drop policy if exists "Admins can read recommendation logs" on public.recommendation_logs;
drop policy if exists "Admins can manage AI briefs" on public.ai_briefs;

create policy "Profiles are readable by owner"
on public.profiles for select using (auth.uid() = id);

create policy "Users update own profile"
on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

create policy "Users can manage own saved articles"
on public.saved_articles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage own reading history"
on public.reading_history for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Anyone can subscribe to newsletter"
on public.newsletter_subscribers for insert
with check (status = 'pending' and confirmed_at is null and unsubscribed_at is null);

create policy "Subscribers can read own email row"
on public.newsletter_subscribers for select using (auth.jwt() ->> 'email' = email);

create policy "Users can manage own preferences"
on public.user_preferences for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "RSS sources are publicly readable"
on public.rss_sources for select using (enabled = true);

create policy "Ad slots are publicly readable"
on public.adsense_slots for select using (enabled = true);

create policy "Approved affiliate links are publicly readable"
on public.affiliate_links for select using (enabled = true);

create policy "Enabled sponsored blocks are publicly readable"
on public.sponsored_blocks for select using (
  enabled = true
  and (start_at is null or start_at <= now())
  and (end_at is null or end_at >= now())
);

create policy "AI settings are publicly readable"
on public.ai_settings for select using (true);

create policy "News cache is publicly readable"
on public.news_cache for select using (true);

create policy "Users can insert analytics events"
on public.analytics_events for insert with check (auth.uid() = user_id or user_id is null);

create policy "Anyone can report corrections"
on public.correction_reports for insert with check (true);

create policy "Admins can manage correction reports"
on public.correction_reports for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage profiles"
on public.profiles for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can read saved articles"
on public.saved_articles for select
using (public.is_admin());

create policy "Admins can read reading history"
on public.reading_history for select
using (public.is_admin());

create policy "Admins can manage rss sources"
on public.rss_sources for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage ad slots"
on public.adsense_slots for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage affiliate links"
on public.affiliate_links for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage sponsored blocks"
on public.sponsored_blocks for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage AI settings"
on public.ai_settings for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage news cache"
on public.news_cache for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage newsletter subscribers"
on public.newsletter_subscribers for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can read user preferences"
on public.user_preferences for select
using (public.is_admin());

create policy "Admins can manage email digest logs"
on public.email_digest_logs for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can read analytics events"
on public.analytics_events for select
using (public.is_admin());

create policy "Admins can read admin logs"
on public.admin_logs for select
using (public.is_admin());

create policy "Admins can insert admin logs"
on public.admin_logs for insert
with check (public.is_admin());

create policy "Active publisher profiles are public"
on public.publisher_profiles for select using (status = 'active');

create policy "Journalist profiles are public"
on public.journalist_profiles for select using (true);

create policy "Published original articles are public"
on public.original_articles for select using (
  status = 'published'
  and (published_at is null or published_at <= now())
);

create policy "Admins can manage publisher profiles"
on public.publisher_profiles for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage journalist profiles"
on public.journalist_profiles for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage original articles"
on public.original_articles for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage original revisions"
on public.original_article_revisions for all
using (public.is_admin())
with check (public.is_admin());

create policy "Admins can manage editorial workflow logs"
on public.editorial_workflow_logs for all
using (public.is_admin())
with check (public.is_admin());

create policy "Users can manage own interests"
on public.user_interests for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage own followed topics"
on public.followed_topics for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage own followed entities"
on public.followed_entities for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage own followed sources"
on public.followed_sources for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can manage own followed authors"
on public.followed_authors for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Users can read own recommendation logs"
on public.recommendation_logs for select using (auth.uid() = user_id);

create policy "Users can insert own recommendation logs"
on public.recommendation_logs for insert with check (auth.uid() = user_id or user_id is null);

create policy "Users can manage own AI briefs"
on public.ai_briefs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "Admins can read user interests"
on public.user_interests for select using (public.is_admin());

create policy "Admins can read followed topics"
on public.followed_topics for select using (public.is_admin());

create policy "Admins can read followed entities"
on public.followed_entities for select using (public.is_admin());

create policy "Admins can read followed sources"
on public.followed_sources for select using (public.is_admin());

create policy "Admins can read followed authors"
on public.followed_authors for select using (public.is_admin());

create policy "Admins can read recommendation logs"
on public.recommendation_logs for select using (public.is_admin());

create policy "Admins can manage AI briefs"
on public.ai_briefs for all using (public.is_admin()) with check (public.is_admin());

create index if not exists saved_articles_user_idx on public.saved_articles(user_id, created_at desc);
create index if not exists reading_history_user_idx on public.reading_history(user_id, read_at desc);
create index if not exists reading_history_article_idx on public.reading_history(article_id, read_at desc);
create index if not exists newsletter_language_idx on public.newsletter_subscribers(language, created_at desc);
create index if not exists newsletter_status_idx on public.newsletter_subscribers(status, frequency, country);
create unique index if not exists newsletter_opt_in_token_idx on public.newsletter_subscribers(opt_in_token) where opt_in_token is not null;
create unique index if not exists newsletter_unsubscribe_token_idx on public.newsletter_subscribers(unsubscribe_token) where unsubscribe_token is not null;
create index if not exists user_preferences_country_idx on public.user_preferences(preferred_country, digest_frequency);
create index if not exists email_digest_logs_status_idx on public.email_digest_logs(status, digest_type, created_at desc);
create index if not exists analytics_event_idx on public.analytics_events(event_name, created_at desc);
create index if not exists analytics_category_idx on public.analytics_events(category, created_at desc);
create index if not exists analytics_article_idx on public.analytics_events(article_id, created_at desc);
create index if not exists correction_reports_status_idx on public.correction_reports(status, created_at desc);
create index if not exists affiliate_category_idx on public.affiliate_links(category, enabled);
create index if not exists sponsored_blocks_active_idx on public.sponsored_blocks(category, placement, enabled, start_at, end_at);
create index if not exists news_cache_lookup_idx on public.news_cache(category, country, published_at desc);
create index if not exists news_cache_updated_idx on public.news_cache(category, country, updated_at desc);
create index if not exists rss_sources_priority_idx on public.rss_sources(category, country, enabled, priority desc);
create index if not exists admin_logs_action_idx on public.admin_logs(action, created_at desc);
create index if not exists admin_logs_status_idx on public.admin_logs(status, created_at desc);
create index if not exists publisher_profiles_slug_idx on public.publisher_profiles(slug, status);
create index if not exists journalist_profiles_slug_idx on public.journalist_profiles(slug, publisher_slug);
create index if not exists original_articles_status_idx on public.original_articles(status, content_type, published_at desc);
create index if not exists original_articles_author_idx on public.original_articles(author_slug, status, published_at desc);
create index if not exists original_articles_publisher_idx on public.original_articles(publisher_slug, status, published_at desc);
create index if not exists original_article_revisions_article_idx on public.original_article_revisions(article_id, created_at desc);
create index if not exists editorial_workflow_logs_article_idx on public.editorial_workflow_logs(article_id, created_at desc);
create index if not exists user_interests_user_idx on public.user_interests(user_id, interest_type, weight desc);
create index if not exists followed_topics_topic_idx on public.followed_topics(topic, created_at desc);
create index if not exists followed_entities_entity_idx on public.followed_entities(entity, created_at desc);
create index if not exists followed_sources_source_idx on public.followed_sources(source, created_at desc);
create index if not exists followed_authors_author_idx on public.followed_authors(author_slug, created_at desc);
create index if not exists recommendation_logs_user_idx on public.recommendation_logs(user_id, created_at desc);
create index if not exists recommendation_logs_article_idx on public.recommendation_logs(article_id, created_at desc);
create index if not exists ai_briefs_user_idx on public.ai_briefs(user_id, brief_type, created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists user_preferences_touch_updated_at on public.user_preferences;
create trigger user_preferences_touch_updated_at
before update on public.user_preferences
for each row execute function public.touch_updated_at();

drop trigger if exists rss_sources_touch_updated_at on public.rss_sources;
create trigger rss_sources_touch_updated_at
before update on public.rss_sources
for each row execute function public.touch_updated_at();

drop trigger if exists adsense_slots_touch_updated_at on public.adsense_slots;
create trigger adsense_slots_touch_updated_at
before update on public.adsense_slots
for each row execute function public.touch_updated_at();

drop trigger if exists affiliate_links_touch_updated_at on public.affiliate_links;
create trigger affiliate_links_touch_updated_at
before update on public.affiliate_links
for each row execute function public.touch_updated_at();

drop trigger if exists sponsored_blocks_touch_updated_at on public.sponsored_blocks;
create trigger sponsored_blocks_touch_updated_at
before update on public.sponsored_blocks
for each row execute function public.touch_updated_at();

drop trigger if exists ai_settings_touch_updated_at on public.ai_settings;
create trigger ai_settings_touch_updated_at
before update on public.ai_settings
for each row execute function public.touch_updated_at();

drop trigger if exists news_cache_touch_updated_at on public.news_cache;
create trigger news_cache_touch_updated_at
before update on public.news_cache
for each row execute function public.touch_updated_at();

drop trigger if exists correction_reports_touch_updated_at on public.correction_reports;
create trigger correction_reports_touch_updated_at
before update on public.correction_reports
for each row execute function public.touch_updated_at();

drop trigger if exists publisher_profiles_touch_updated_at on public.publisher_profiles;
create trigger publisher_profiles_touch_updated_at
before update on public.publisher_profiles
for each row execute function public.touch_updated_at();

drop trigger if exists journalist_profiles_touch_updated_at on public.journalist_profiles;
create trigger journalist_profiles_touch_updated_at
before update on public.journalist_profiles
for each row execute function public.touch_updated_at();

drop trigger if exists original_articles_touch_updated_at on public.original_articles;
create trigger original_articles_touch_updated_at
before update on public.original_articles
for each row execute function public.touch_updated_at();

drop trigger if exists user_interests_touch_updated_at on public.user_interests;
create trigger user_interests_touch_updated_at
before update on public.user_interests
for each row execute function public.touch_updated_at();

drop trigger if exists ai_briefs_touch_updated_at on public.ai_briefs;
create trigger ai_briefs_touch_updated_at
before update on public.ai_briefs
for each row execute function public.touch_updated_at();

create or replace function public.cleanup_old_events(days_to_keep integer default 180)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  if not public.is_admin() then
    raise exception 'Admin role required';
  end if;

  delete from public.analytics_events
  where created_at < now() - make_interval(days => greatest(days_to_keep, 30));

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

create or replace function public.cleanup_old_reading_history(days_to_keep integer default 365)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  deleted_count integer;
begin
  if not public.is_admin() then
    raise exception 'Admin role required';
  end if;

  delete from public.reading_history
  where read_at < now() - make_interval(days => greatest(days_to_keep, 90));

  get diagnostics deleted_count = row_count;
  return deleted_count;
end;
$$;

insert into public.rss_sources (name, category, url, language, country)
values
  ('Google News India Local', 'local', 'https://news.google.com/rss/search?q=India&hl=en-IN&gl=IN&ceid=IN:en', 'en', 'IN'),
  ('Google News US Local', 'local', 'https://news.google.com/rss/search?q=United%20States&hl=en-US&gl=US&ceid=US:en', 'en', 'US'),
  ('Google News India Top', 'top', 'https://news.google.com/rss?hl=en-IN&gl=IN&ceid=IN:en', 'en', 'IN'),
  ('Google News World', 'world', 'https://news.google.com/rss/headlines/section/topic/WORLD?hl=en-IN&gl=IN&ceid=IN:en', 'en', 'IN'),
  ('Google News YouTube Live', 'live', 'https://news.google.com/rss/search?q=site%3Ayoutube.com%2Fwatch%20live%20news%20India&hl=en-IN&gl=IN&ceid=IN:en', 'en', 'IN'),
  ('Google News YouTube Video', 'video', 'https://news.google.com/rss/search?q=site%3Ayoutube.com%20video%20news%20India&hl=en-IN&gl=IN&ceid=IN:en', 'en', 'IN')
on conflict (url) do nothing;

insert into public.publisher_profiles (slug, name, logo_url, homepage_url, country, categories, credibility_profile, status)
values
  ('nuzenio', 'Nuzenio', '/icon.svg', 'https://nuzenio.com/', 'GLOBAL', array['news intelligence','analysis','fact-checks','research'], '{"labels":["Editorial brand","Original journalism foundation","Corrections workflow"]}'::jsonb, 'active'),
  ('reuters', 'Reuters', 'https://www.google.com/s2/favicons?domain=reuters.com&sz=256', 'https://www.reuters.com/', 'GLOBAL', array['world','business','markets'], '{"labels":["Verified publisher","Global wire service","Multi-region coverage"]}'::jsonb, 'active'),
  ('associated-press', 'Associated Press', 'https://www.google.com/s2/favicons?domain=apnews.com&sz=256', 'https://apnews.com/', 'US', array['world','politics','sports'], '{"labels":["Verified publisher","Wire service","Original reporting"]}'::jsonb, 'active'),
  ('bbc-news', 'BBC News', 'https://www.google.com/s2/favicons?domain=bbc.com&sz=256', 'https://www.bbc.com/news', 'GB', array['world','uk','science'], '{"labels":["Verified publisher","Public service broadcaster","International desk"]}'::jsonb, 'active'),
  ('the-guardian', 'The Guardian', 'https://www.google.com/s2/favicons?domain=theguardian.com&sz=256', 'https://www.theguardian.com/', 'GB', array['world','climate','culture'], '{"labels":["Verified publisher","Editorial transparency","Global coverage"]}'::jsonb, 'active'),
  ('al-jazeera', 'Al Jazeera', 'https://www.google.com/s2/favicons?domain=aljazeera.com&sz=256', 'https://www.aljazeera.com/', 'GLOBAL', array['world','middle east','live'], '{"labels":["Verified publisher","International coverage","Developing stories"]}'::jsonb, 'active'),
  ('the-hindu', 'The Hindu', 'https://www.google.com/s2/favicons?domain=thehindu.com&sz=256', 'https://www.thehindu.com/', 'IN', array['india','business','science'], '{"labels":["Verified publisher","India source","Editorial archive"]}'::jsonb, 'active'),
  ('ndtv', 'NDTV', 'https://www.google.com/s2/favicons?domain=ndtv.com&sz=256', 'https://www.ndtv.com/', 'IN', array['india','live','video'], '{"labels":["Verified publisher","India source","Video coverage"]}'::jsonb, 'active'),
  ('nikkei-asia', 'Nikkei Asia', 'https://www.google.com/s2/favicons?domain=asia.nikkei.com&sz=256', 'https://asia.nikkei.com/', 'JP', array['asia','business','technology'], '{"labels":["Verified publisher","Asia business focus","Markets coverage"]}'::jsonb, 'active'),
  ('cbc-news', 'CBC News', 'https://www.google.com/s2/favicons?domain=cbc.ca&sz=256', 'https://www.cbc.ca/news', 'CA', array['canada','world','local'], '{"labels":["Verified publisher","Public broadcaster","Local coverage"]}'::jsonb, 'active'),
  ('abc-news-au', 'ABC News Australia', 'https://www.google.com/s2/favicons?domain=abc.net.au&sz=256', 'https://www.abc.net.au/news', 'AU', array['australia','world','science'], '{"labels":["Verified publisher","Public broadcaster","Regional coverage"]}'::jsonb, 'active')
on conflict (slug) do update set
  name = excluded.name,
  logo_url = excluded.logo_url,
  homepage_url = excluded.homepage_url,
  country = excluded.country,
  categories = excluded.categories,
  credibility_profile = excluded.credibility_profile,
  status = excluded.status;

insert into public.journalist_profiles (slug, full_name, role, bio, publisher_slug, expertise)
values
  ('nuzenio-news-desk', 'Nuzenio News Desk', 'Editorial desk', 'Maintains publisher attribution, story routing, live feed quality, corrections, and reader-first news presentation.', 'nuzenio', array['live rss curation','source attribution','breaking news routing']),
  ('nuzenio-analysis-team', 'Nuzenio Analysis Team', 'Analysis desk', 'Prepares original analysis and explainers when editorial approval and source evidence are available.', 'nuzenio', array['explainers','context','timeline analysis']),
  ('nuzenio-fact-check-desk', 'Nuzenio Fact-Check Desk', 'Fact-check desk', 'Owns correction review, claim context, source comparison, and fact-check labeling workflows.', 'nuzenio', array['claims','corrections','verification status']),
  ('nuzenio-research-desk', 'Nuzenio Research Desk', 'Research desk', 'Supports premium reports, research hubs, source intelligence, and partner publisher programs.', 'nuzenio', array['research reports','topic hubs','source intelligence'])
on conflict (slug) do update set
  full_name = excluded.full_name,
  role = excluded.role,
  bio = excluded.bio,
  publisher_slug = excluded.publisher_slug,
  expertise = excluded.expertise;

insert into public.adsense_slots (slot_key, placement, format, notes)
values
  ('top-native', 'Home feed top', 'native', 'Reserved until AdSense approval.'),
  ('sidebar-rectangle', 'Desktop right rail', 'rectangle', 'Reserved until AdSense approval.'),
  ('article-inline', 'Article detail body', 'responsive', 'Add publisher script after policy review.'),
  ('header-leaderboard', 'Header below navigation', 'leaderboard', 'Policy-safe top ad with clear spacing.'),
  ('footer-banner', 'Footer above site links', 'banner', 'Footer ad slot away from interactive buttons.'),
  ('mobile-feed', 'Mobile feed after story cards', 'responsive', 'Mobile-first revenue slot.'),
  ('newsletter-sponsor', 'Daily brief sponsorship', 'sponsor', 'Sponsor slot for newsletter campaigns.')
on conflict (slot_key) do nothing;

insert into public.ai_settings (key, enabled, categories, simple_brief_enabled, comparison_enabled)
values ('global', true, array['top','world','business','tech','ai','sports','health','science','entertainment','local'], true, true)
on conflict (key) do nothing;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    new.raw_user_meta_data ->> 'full_name',
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();
