export const evergreenHubs = [
  { slug: 'ai', aliases: ['ai-hub'], label: 'AI Hub', category: 'ai', query: 'artificial intelligence AI OpenAI Google Anthropic Nvidia chips models policy startups', intent: 'Evergreen AI intelligence hub for models, chips, tools, policy, companies, and research.' },
  { slug: 'space', aliases: ['space-hub'], label: 'Space Hub', category: 'science', query: 'space NASA rocket satellite moon mars astronomy launch mission', intent: 'Evergreen space intelligence hub for launches, satellites, missions, NASA, moon, Mars, and astronomy.' },
  { slug: 'climate', aliases: ['climate-hub'], label: 'Climate Hub', category: 'science', query: 'climate change weather emissions energy transition heat floods policy', intent: 'Evergreen climate intelligence hub for climate science, policy, weather, emissions, and energy transition.' },
  { slug: 'economy', aliases: ['economy-hub'], label: 'Economy Hub', category: 'business', query: 'economy inflation jobs GDP central bank interest rates trade recession growth', intent: 'Evergreen economy intelligence hub for inflation, jobs, GDP, central banks, trade, and growth.' },
  { slug: 'startup', aliases: ['startup-hub', 'startups-hub'], label: 'Startup Hub', category: 'business', query: 'startups startup venture capital funding founders IPO technology companies', intent: 'Evergreen startup intelligence hub for funding, founders, venture capital, IPOs, and startup markets.' },
];

export const publisherDirectory = [
  {
    slug: 'reuters',
    name: 'Reuters',
    country: 'GLOBAL',
    homepage: 'https://www.reuters.com/',
    logo: 'https://www.google.com/s2/favicons?domain=reuters.com&sz=256',
    categories: ['World', 'Business', 'Markets'],
    credibility: ['Verified publisher', 'Global wire service', 'Multi-region coverage'],
    profile: 'Reuters is tracked on Nuzenio as a global publisher source for breaking, business, markets, and international news signals.',
  },
  {
    slug: 'associated-press',
    name: 'Associated Press',
    country: 'US',
    homepage: 'https://apnews.com/',
    logo: 'https://www.google.com/s2/favicons?domain=apnews.com&sz=256',
    categories: ['World', 'Politics', 'Sports'],
    credibility: ['Verified publisher', 'Wire service', 'Original reporting'],
    profile: 'Associated Press coverage is used for source comparison, fast reporting signals, and broad public-interest news discovery.',
  },
  {
    slug: 'bbc-news',
    name: 'BBC News',
    country: 'GB',
    homepage: 'https://www.bbc.com/news',
    logo: 'https://www.google.com/s2/favicons?domain=bbc.com&sz=256',
    categories: ['World', 'UK', 'Science'],
    credibility: ['Verified publisher', 'Public service broadcaster', 'International desk'],
    profile: 'BBC News is tracked for international, public-service, science, business, and culture coverage across regions.',
  },
  {
    slug: 'the-guardian',
    name: 'The Guardian',
    country: 'GB',
    homepage: 'https://www.theguardian.com/',
    logo: 'https://www.google.com/s2/favicons?domain=theguardian.com&sz=256',
    categories: ['World', 'Climate', 'Culture'],
    credibility: ['Verified publisher', 'Editorial transparency', 'Global coverage'],
    profile: 'The Guardian is tracked for global reporting, climate, culture, politics, and long-running developing stories.',
  },
  {
    slug: 'al-jazeera',
    name: 'Al Jazeera',
    country: 'GLOBAL',
    homepage: 'https://www.aljazeera.com/',
    logo: 'https://www.google.com/s2/favicons?domain=aljazeera.com&sz=256',
    categories: ['World', 'Middle East', 'Live'],
    credibility: ['Verified publisher', 'International coverage', 'Developing stories'],
    profile: 'Al Jazeera is tracked for international coverage, live updates, and developing stories across major regions.',
  },
  {
    slug: 'the-hindu',
    name: 'The Hindu',
    country: 'IN',
    homepage: 'https://www.thehindu.com/',
    logo: 'https://www.google.com/s2/favicons?domain=thehindu.com&sz=256',
    categories: ['India', 'Business', 'Science'],
    credibility: ['Verified publisher', 'India source', 'Editorial archive'],
    profile: 'The Hindu is tracked for India-focused public-interest reporting, policy, business, science, and regional coverage.',
  },
  {
    slug: 'ndtv',
    name: 'NDTV',
    country: 'IN',
    homepage: 'https://www.ndtv.com/',
    logo: 'https://www.google.com/s2/favicons?domain=ndtv.com&sz=256',
    categories: ['India', 'Live', 'Video'],
    credibility: ['Verified publisher', 'India source', 'Video coverage'],
    profile: 'NDTV is tracked for India headlines, live news, video signals, local interest, and national developing stories.',
  },
  {
    slug: 'nikkei-asia',
    name: 'Nikkei Asia',
    country: 'JP',
    homepage: 'https://asia.nikkei.com/',
    logo: 'https://www.google.com/s2/favicons?domain=asia.nikkei.com&sz=256',
    categories: ['Asia', 'Business', 'Technology'],
    credibility: ['Verified publisher', 'Asia business focus', 'Markets coverage'],
    profile: 'Nikkei Asia is tracked for Asia business, markets, geopolitics, technology, and company intelligence.',
  },
  {
    slug: 'cbc-news',
    name: 'CBC News',
    country: 'CA',
    homepage: 'https://www.cbc.ca/news',
    logo: 'https://www.google.com/s2/favicons?domain=cbc.ca&sz=256',
    categories: ['Canada', 'World', 'Local'],
    credibility: ['Verified publisher', 'Public broadcaster', 'Local coverage'],
    profile: 'CBC News is tracked for Canadian public-interest reporting, local coverage, national affairs, and world headlines.',
  },
  {
    slug: 'abc-news-au',
    name: 'ABC News Australia',
    country: 'AU',
    homepage: 'https://www.abc.net.au/news',
    logo: 'https://www.google.com/s2/favicons?domain=abc.net.au&sz=256',
    categories: ['Australia', 'World', 'Science'],
    credibility: ['Verified publisher', 'Public broadcaster', 'Regional coverage'],
    profile: 'ABC News Australia is tracked for Australian public-interest reporting, regional coverage, science, and world news.',
  },
];

export const authorDirectory = [
  {
    slug: 'nuzenio-news-desk',
    name: 'Nuzenio News Desk',
    role: 'Editorial desk',
    publisher: 'Nuzenio',
    expertise: ['Live RSS curation', 'Source attribution', 'Breaking news routing'],
    bio: 'The Nuzenio News Desk maintains publisher attribution, story routing, live feed quality, corrections, and reader-first news presentation.',
  },
  {
    slug: 'nuzenio-analysis-team',
    name: 'Nuzenio Analysis Team',
    role: 'Analysis desk',
    publisher: 'Nuzenio',
    expertise: ['Explainers', 'Context', 'Timeline analysis'],
    bio: 'The Nuzenio Analysis Team prepares original analysis and explainers when editorial approval and source evidence are available.',
  },
  {
    slug: 'nuzenio-fact-check-desk',
    name: 'Nuzenio Fact-Check Desk',
    role: 'Fact-check desk',
    publisher: 'Nuzenio',
    expertise: ['Claims', 'Corrections', 'Verification status'],
    bio: 'The Nuzenio Fact-Check Desk owns correction review, claim context, source comparison, and fact-check labeling workflows.',
  },
  {
    slug: 'nuzenio-research-desk',
    name: 'Nuzenio Research Desk',
    role: 'Research desk',
    publisher: 'Nuzenio',
    expertise: ['Research reports', 'Topic hubs', 'Source intelligence'],
    bio: 'The Nuzenio Research Desk supports premium reports, research hubs, source intelligence, and partner publisher programs.',
  },
];

export const entitySeeds = [
  'OpenAI',
  'Google',
  'Microsoft',
  'Nvidia',
  'Apple',
  'Tesla',
  'Amazon',
  'Meta',
  'United Nations',
  'World Health Organization',
  'Federal Reserve',
  'European Union',
  'NASA',
  'India',
  'United States',
];

const enableAdvancedIntelligenceRoutes = false;

export const dataPlatformPages = enableAdvancedIntelligenceRoutes ? [
  {
    slug: 'data-platform',
    label: 'News Data Platform',
    category: 'top',
    query: 'global news data intelligence entities trends',
    intent: 'Nuzenio public API, knowledge graph, story graph, archive, and enterprise news intelligence infrastructure.',
  },
] : [];

export const ecosystemModules = [
  {
    slug: 'publisher-portal',
    title: 'Publisher Portal',
    text: 'Publisher accounts, feed submission, verification review, source quality, and publisher analytics.',
    metrics: ['RSS feed submission', 'Verification process', 'Analytics dashboard'],
    href: '/publisher-portal',
  },
  {
    slug: 'journalist-portal',
    title: 'Journalist Portal',
    text: 'Author identity, publishing tools, audience analytics, profile verification, and badges.',
    metrics: ['Author profiles', 'Publishing tools', 'Verification badges'],
    href: '/journalist-portal',
  },
  {
    slug: 'research-hub',
    title: 'Research Hub',
    text: 'Deep reports, historical archives, topic intelligence, story timelines, and data downloads.',
    metrics: ['Research reports', 'Historical archive', 'CSV/JSON/PDF exports'],
    href: '/research-hub',
  },
  {
    slug: 'api-marketplace',
    title: 'API Marketplace',
    text: 'News API, Trends API, Entity API, Intelligence API, usage quotas, and developer access.',
    metrics: ['/api/v1/latest', '/api/v1/trends', '/api/v1/entities'],
    href: '/api-marketplace',
  },
  {
    slug: 'enterprise',
    title: 'Enterprise Platform',
    text: 'Custom feeds, organization dashboards, custom alerts, shared reports, and team workflows.',
    metrics: ['Custom feeds', 'Team dashboards', 'Shared alerts'],
    href: '/enterprise',
  },
  {
    slug: 'ai-research-assistant',
    title: 'AI Research Assistant',
    text: 'Ask questions, generate timelines, compare publisher coverage, and summarize topics with source links.',
    metrics: ['Questions', 'Timelines', 'Source comparison'],
    href: '/ai-research-assistant',
  },
  {
    slug: 'knowledge-graph',
    title: 'Global Knowledge Graph',
    text: 'News entities, relationships, story clusters, event chains, and timeline tracking.',
    metrics: ['Entities', 'Relationships', 'Events'],
    href: '/knowledge-graph',
  },
  {
    slug: 'integrations',
    title: 'Ecosystem Integrations',
    text: 'Slack, Teams, email, webhooks, and CRM delivery for alerts and reports.',
    metrics: ['Slack', 'Teams', 'Webhooks'],
    href: '/integrations',
  },
];

export const marketplaceProducts = [
  ['News API Pro', 'Higher-quota latest news, search, trends, entities, graph, and intelligence endpoints.', '$49/mo starter'],
  ['Enterprise Intelligence Feed', 'Custom country, topic, entity, publisher, and alert feeds for organizations.', 'Sales approval'],
  ['Premium Research Datasets', 'Export-ready datasets for research, media monitoring, and market analysis.', 'Enterprise'],
  ['Partner Integrations Pack', 'Slack, Teams, email, webhook, and CRM delivery setup.', 'Enterprise'],
];
